version: "3.8"

services:
  postgresql:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=256MB"

  fastapi:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    environment:
      - user=${POSTGRES_USER}
      - password=${POSTGRES_PASSWORD}
      - database=${POSTGRES_DB}
      - host=postgresql
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}  # Add your AWS access key here
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}  # Add your AWS secret key here
      - AWS_REGION=us-west-2

